print("okay~~~~~~~~~~~!")
print('changed_YK!!!')
print("What is wrong with it?!")
print('YKYK!!!')
print("What are we goint to have as our dinner?!")
print('herehere!!!!')
print("!!!!!!!!!!!==========!!!!!!!!!!")