print("okay~~~~~~~~~~~!")
print('changed_YK!!!')
print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`")
print('YKYK!!!')
print("What are we goint to have as our dinner?!")
print('herehere!!!!')
print("!!!!!!!!!!!==========!!!!!!!!!!")